# Generated by Django 4.2.5 on 2023-10-25 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A2p_Body_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('details', models.TextField(null=True)),
                ('contact', models.CharField(max_length=50, null=True)),
                ('features', models.CharField(max_length=50, null=True)),
                ('vas_title', models.CharField(max_length=50, null=True)),
                ('work_title', models.CharField(max_length=50, null=True)),
                ('work_bottom', models.CharField(max_length=50, null=True)),
                ('details2', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'A2p Body Content',
            },
        ),
        migrations.CreateModel(
            name='A2p_KloudSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('details', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'A2p Kloud SMS',
            },
        ),
        migrations.CreateModel(
            name='A2p_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('picture', models.ImageField(default='avatar.svg', null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'A2p Slider',
            },
        ),
        migrations.CreateModel(
            name='A2pSMS_Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_title', models.CharField(max_length=60, null=True)),
                ('feature_details', models.TextField(null=True)),
                ('feature_icone', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'A2p SMS Feature',
            },
        ),
        migrations.CreateModel(
            name='Boardcast_Bottom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('details', models.TextField(null=True)),
                ('picture', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('demo', models.CharField(max_length=25, null=True)),
            ],
            options={
                'verbose_name_plural': 'Boardcast Bottom',
            },
        ),
        migrations.CreateModel(
            name='Boardcast_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('details', models.TextField(null=True)),
                ('picture', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('demo', models.CharField(max_length=25, null=True)),
            ],
            options={
                'verbose_name_plural': 'Boardcast Content',
            },
        ),
        migrations.CreateModel(
            name='Boardcast_Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('details', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Boardcast Manue',
            },
        ),
        migrations.CreateModel(
            name='Boardcast_Top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('details', models.TextField(null=True)),
                ('picture', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('site_title', models.CharField(max_length=50, null=True)),
                ('site_details', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Boardcast Top',
            },
        ),
        migrations.CreateModel(
            name='Contact_Headquarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, null=True)),
                ('phone_no', models.CharField(max_length=20, null=True)),
                ('email_address', models.EmailField(max_length=50, null=True)),
                ('branch_address', models.TextField(max_length=200, null=True)),
                ('branch_ph_no', models.CharField(max_length=20, null=True)),
                ('branch_email', models.EmailField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Headquarter',
            },
        ),
        migrations.CreateModel(
            name='Contact_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=20, null=True)),
                ('email_address', models.EmailField(max_length=50, null=True)),
                ('address', models.TextField(max_length=200, null=True)),
                ('header_ph_no', models.CharField(max_length=20, null=True)),
                ('header_email', models.EmailField(max_length=50, null=True)),
                ('logo', models.ImageField(default='avatar.svg', null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='Contact_U',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('messages', models.TextField(null=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Home_body_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title1', models.CharField(max_length=40, null=True)),
                ('top_title2', models.CharField(max_length=40, null=True)),
                ('help_title', models.CharField(max_length=40, null=True)),
                ('details', models.TextField(null=True)),
                ('picture', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('bottom_title', models.CharField(max_length=50, null=True)),
                ('bottom_details', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Home Body Content',
            },
        ),
        migrations.CreateModel(
            name='Home_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150, null=True)),
                ('answer', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Home Question',
            },
        ),
        migrations.CreateModel(
            name='Home_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=60, null=True)),
                ('service_details', models.TextField(null=True)),
                ('service_icone', models.CharField(max_length=60, null=True)),
            ],
            options={
                'verbose_name_plural': 'Home Services',
            },
        ),
        migrations.CreateModel(
            name='Home_SMS_Terminated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Terminated_title', models.CharField(max_length=48, null=True)),
                ('Satisfied_Clients', models.CharField(max_length=7, null=True)),
                ('Increased_Traffic', models.CharField(max_length=7, null=True)),
                ('Increased_Revenue', models.CharField(max_length=7, null=True)),
                ('ANNUAL_TURNOVER', models.CharField(max_length=7, null=True)),
            ],
            options={
                'verbose_name_plural': 'Home SMS Terminated',
            },
        ),
        migrations.CreateModel(
            name='Sms_Bottom_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('details', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'SMS Bottom Content',
            },
        ),
        migrations.CreateModel(
            name='Sms_Choose_U',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('point_1', models.CharField(max_length=200, null=True)),
                ('point_2', models.CharField(max_length=150, null=True)),
                ('point_3', models.CharField(max_length=150)),
                ('point_4', models.CharField(max_length=150)),
                ('point_5', models.CharField(max_length=150)),
                ('picture', models.ImageField(default='avatar.svg', null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'SMS Choose Us',
            },
        ),
        migrations.CreateModel(
            name='Sms_Switch_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('details', models.TextField(null=True)),
                ('picture', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('service_title', models.CharField(max_length=50, null=True)),
                ('service_details', models.CharField(max_length=80, null=True)),
            ],
            options={
                'verbose_name_plural': 'SMS Switch Contact',
            },
        ),
        migrations.CreateModel(
            name='Sms_Switch_Manue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, null=True)),
                ('details', models.TextField(null=True)),
                ('icone', models.CharField(max_length=60, null=True)),
            ],
            options={
                'verbose_name_plural': 'SMS Switch Manue',
            },
        ),
        migrations.CreateModel(
            name='Voice_otp_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('details', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Voice OTP Content',
            },
        ),
        migrations.CreateModel(
            name='Voice_Otp_Manue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, null=True)),
                ('details', models.TextField(null=True)),
                ('icone', models.CharField(max_length=60, null=True)),
            ],
            options={
                'verbose_name_plural': 'Voice OTP Manue',
            },
        ),
        migrations.CreateModel(
            name='Voice_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150, null=True)),
                ('answer', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Voice Questions',
            },
        ),
        migrations.CreateModel(
            name='VoiceOtp_Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('details', models.TextField(null=True)),
                ('title2', models.CharField(max_length=50, null=True)),
                ('details2', models.CharField(max_length=320, null=True)),
                ('details3', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Voice OTP Body',
            },
        ),
        migrations.CreateModel(
            name='Wifi_bottom_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, null=True)),
                ('details', models.TextField(null=True)),
                ('demo', models.CharField(max_length=60, null=True)),
            ],
            options={
                'verbose_name_plural': 'Wifi Bottom Content',
            },
        ),
        migrations.CreateModel(
            name='Wifi_bottom_Manue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, null=True)),
                ('details', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Wifi Bottom Manue',
            },
        ),
        migrations.CreateModel(
            name='Wifi_Control_Manue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, null=True)),
                ('details', models.TextField(null=True)),
                ('icone', models.CharField(max_length=60, null=True)),
            ],
            options={
                'verbose_name_plural': 'Wifi Control Manue',
            },
        ),
        migrations.CreateModel(
            name='WifiSoulation_body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_details', models.TextField(null=True)),
                ('details2', models.CharField(max_length=350, null=True)),
                ('picture', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('mid_title', models.CharField(max_length=250, null=True)),
                ('mid_details', models.CharField(max_length=350, null=True)),
                ('picture2', models.ImageField(default='avatar.svg', null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Wifi Soulation Body',
            },
        ),
    ]
